### ISSUE TITLE
500 Internal Server Error during login via OIDC (Keycloak)

### ISSUE THREAD

**Issue by Diogo-Rego** [MISP/misp-docker#163]
**Description:** While attempting to log into MISP using OpenID Connect (OIDC) with Keycloak as the identity provider, an "Internal Error Has Occurred" message was displayed. The error seems related to a failure in email sending and an issue with validating the authentication state via OIDC.

**Steps to reproduce:**

1. Navigate to the MISP login page.
2. Attempt to log in using OIDC credentials via Keycloak.
3. The system returns a "500 Internal Server Error" page.

**Expected behavior:** The login should complete successfully, and the user should be redirected to the MISP dashboard.

**Actual behavior:** The login fails, and an "Internal Error Has Occurred" message is displayed.

**Screenshot:** <insert the screenshot here, such as the previously generated file>

**Error Logs:**

```sh
root@test-misp-core-8695499f96-fc5ck:/var/www/MISP/app/tmp/logs# cat error.log 
2024-10-03 19:48:56 Error: Exception during sending e-mail with subject '[ MISP] New sign in.' to nexus@test.com
[SendEmailException] The message could not be sent.
Stack Trace:
#0 /var/www/MISP/app/Model/User.php(887): SendEmail->sendToUser()
#1 /var/www/MISP/app/Model/UserLoginProfile.php(273): User->sendEmail()
#2 /var/www/MISP/app/Controller/UsersController.php(1320): UserLoginProfile->emailNewLogin()
#3 /var/www/MISP/app/Controller/UsersController.php(1260): UsersController->_postlogin()
#4 [internal function]: UsersController->login()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#8 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#9 {main}
[SocketException] php_network_getaddresses: getaddrinfo failed: Name or service not known
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Email/SmtpTransport.php(146): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Email/SmtpTransport.php(86): SmtpTransport->_connect()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Email/CakeEmail.php(1183): SmtpTransport->send()
#3 /var/www/MISP/app/Lib/Tools/SendEmail.php(156): CakeEmail->send()
#4 /var/www/MISP/app/Lib/Tools/SendEmail.php(558): CakeEmailExtended->send()
#5 /var/www/MISP/app/Model/User.php(887): SendEmail->sendToUser()
#6 /var/www/MISP/app/Model/UserLoginProfile.php(273): User->sendEmail()
#7 /var/www/MISP/app/Controller/UsersController.php(1320): UserLoginProfile->emailNewLogin()
#8 /var/www/MISP/app/Controller/UsersController.php(1260): UsersController->_postlogin()
#9 [internal function]: UsersController->login()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#12 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#13 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#14 {main}
2024-10-03 19:49:42 Error: [JakubOnderka\OpenIDConnectClientException] State is not set in session
Request URL: /users/login?state=Xm4So10c3SO0tHB77qNrVQ&session_state=11f81b49-bbf1-47ef-8048-acb7fce0a8d5&iss=https%3A%2F%2Fid.test.com%2Frealms%2FMISP&code=9c1be10d-0243-4cfc-a91e-338fd87e2323.11f81b49-bbf1-47ef-8048-acb7fce0a8d5.bbdd1153-1d10-4691-b6ff-80e77d054aa9
Stack Trace:
#0 /var/www/MISP/app/Vendor/jakub-onderka/openid-connect-php/src/OpenIDConnectClient.php(468): JakubOnderka\OpenIDConnectClient->validateStateFromSession()
#1 /var/www/MISP/app/Plugin/OidcAuth/Lib/Oidc.php(24): JakubOnderka\OpenIDConnectClient->authenticate()
#2 /var/www/MISP/app/Plugin/OidcAuth/Controller/Component/Auth/OidcAuthenticate.php(34): Oidc->authenticate()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(772): OidcAuthenticate->authenticate()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(612): AuthComponent->identify()
#5 /var/www/MISP/app/Controller/UsersController.php(1252): AuthComponent->login()
#6 [internal function]: UsersController->login()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#11 {main}
2024-10-03 19:49:42 Error: [MissingControllerException] Controller class CssController could not be found.
Exception Attributes: array (
  'class' => 'CssController',
  'plugin' => NULL,
)
Request URL: /css/bootstrap-datepicker.css.map
Stack Trace:
#0 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#1 {main}
2024-10-03 19:49:43 Error: [JakubOnderka\OpenIDConnectClientException] State is not set in session
Request URL: /users/login?state=tc0XBhk-FxmO2paWGlRiUg&session_state=11f81b49-bbf1-47ef-8048-acb7fce0a8d5&iss=https%3A%2F%2Fid.test.com%2Frealms%2FMISP&code=9d0d451d-c5f1-4a69-af18-50c45f0dd07b.11f81b49-bbf1-47ef-8048-acb7fce0a8d5.bbdd1153-1d10-4691-b6ff-80e77d054aa9
Stack Trace:
#0 /var/www/MISP/app/Vendor/jakub-onderka/openid-connect-php/src/OpenIDConnectClient.php(468): JakubOnderka\OpenIDConnectClient->validateStateFromSession()
#1 /var/www/MISP/app/Plugin/OidcAuth/Lib/Oidc.php(24): JakubOnderka\OpenIDConnectClient->authenticate()
#2 /var/www/MISP/app/Plugin/OidcAuth/Controller/Component/Auth/OidcAuthenticate.php(34): Oidc->authenticate()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(772): OidcAuthenticate->authenticate()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(612): AuthComponent->identify()
#5 /var/www/MISP/app/Controller/UsersController.php(1252): AuthComponent->login()
#6 [internal function]: UsersController->login()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#10 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
#11 {main}
```

**Likely Cause:**

1. Email sending failure (likely related to SMTP configuration issues).
2. OIDC state validation is not being handled correctly, leading to authentication failure.

**Possible Solutions:**

* Verify and adjust SMTP settings to resolve the email sending failure.
* Check the OpenID Connect implementation with Keycloak to ensure the state is being properly set and validated during the login process.

**Environment:**

* System: MISP
* Version: v2.4.198
* Identity Provider: Keycloak
* Browser: google-chrome
* OS: debian

**Comment by Diogo-Rego** [comment]
@ostefano Do you know anything about these errors?

**Comment by ostefano** [comment]
No idea unfortunately.

We use OIDC internally buy I resorted to implementing my own OIDC plugin so I could debug things properly.

I will close this, since it's not related to the docker image itself.
