### ISSUE TITLE
Starting fetch from Feed - Results in Error: Database connection "Mysql" is missing, or could not be created.

### ISSUE THREAD

**Issue by HachimanSec** [MISP/misp-docker#38]
Hello, 

I just pulled the docker image to setup a MISP instance. 

Most of the things work fine but while fetching and caching the various feed, I receive alot of MySQL errors. 
Strangely some feeds are finished without any problems and events are published. 

I havent modified the MySQL settings in .env. 

Something I am missing or is it RTFM error?
 ```
Error: Error: Database connection "Mysql" is missing, or could not be created.
[(Click to hide stack trace)](https://10.10.1.10/jobs/index#)
Error: Database connection "Mysql" is missing, or could not be created.
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(278): Mysql->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3659): ConnectionManager::getDataSource()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1162): Model->setDataSource()
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3686): Model->setSource()
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(1394): Model->getDataSource()
#6 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(283): Model->schema()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init()
#10 /var/www/MISP/app/Model/AppModel.php(113): Model->__construct()
#11 /var/www/MISP/app/Model/User.php(239): AppModel->__construct()
#12 [internal function]: User->__construct()
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#14 /var/www/MISP/app/Plugin/SysLogLogable/Model/Behavior/SysLogLogableBehavior.php(279): ClassRegistry::init()
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(145): SysLogLogableBehavior->setup()
#16 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/BehaviorCollection.php(66): BehaviorCollection->load()
#17 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(781): BehaviorCollection->init()
#18 /var/www/MISP/app/Model/AppModel.php(113): Model->__construct()
#19 /var/www/MISP/app/Model/Server.php(191): AppModel->__construct()
#20 [internal function]: Server->__construct()
#21 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ClassRegistry.php(169): ReflectionClass->newInstance()
#22 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(316): ClassRegistry::init()
#23 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(269): Shell->loadModel()
#24 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(228): Shell->_loadModels()
#25 /var/www/MISP/app/Console/Command/AppShell.php(42): Shell->initialize()
#26 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(221): AppShell->initialize()
#27 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#28 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#29 {main}
```

![Screenshot 2024-04-02 at 16 03 26](https://github.com/MISP/misp-docker/assets/20123996/7417216a-9dae-42c7-a371-b7c85d70afe3)

Thx for any hint!

**Comment by ostefano** [comment]
Weird, what if you run them again? I would ask on Gitter, and specifically the MISP rooms (doubt it's related to Docker, even though you never know these days...)

**Comment by HachimanSec** [comment]
Same behaviour. Some go through some are stuck. 

But I just saw that some older fetches are still hanging. Plus there is some error in the Diagnostics - yet I don't know whether this is related. 
![Screenshot 2024-04-02 at 16 16 17](https://github.com/MISP/misp-docker/assets/20123996/abbbeb5c-c7ae-41c2-8d01-aea68ca4307a)

PS: Sorry, it actually does work to start the feed again. Strange
![Screenshot 2024-04-02 at 16 18 51](https://github.com/MISP/misp-docker/assets/20123996/7dc0ab6b-6613-44fe-b9ff-5e7653c37036)

**Comment by ostefano** [comment]
I would explore this in the MISP Gitter/Matrix chats.

**Comment by HachimanSec** [comment]
Thx for the hint. Unfortunately I am back to square 1 with the feeds. 
Pretty strange. 
![Screenshot 2024-04-02 at 17 31 17](https://github.com/MISP/misp-docker/assets/20123996/a0e0ab9c-4ced-4e3a-b948-c3c78ced3a75)

**Comment by ostefano** [comment]
I am closing this since it looks like an issue unrelated to the docker image.
